---
- name: Install Jenkins on EC2
  hosts: amazon
  become: true
  become_user: root
 
  tasks:
  - name: Update all packages
    yum :
      name: '*'
      state: latest
  - name: Install Git
    yum :
      name: git
      state: latest
  - name: Install Docker
    yum :
      name: docker
      state: latest
  - name: Install openJDK 8
    yum :
      name: java-1.8.0-openjdk
      state: latest
  - shell: echo JAVA_HOME is $JAVA_HOME
    environment:
      JAVA_HOME: /usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.181-3.b13.amzn2.x86_64
    register: shellout
  - debug: var=shellout
  - name: Download Jenkins
    get_url:
      url : http://pkg.jenkins.io/redhat/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Install Jenkins
    shell : |
      rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
      yum install jenkins -y
      service jenkins start
  - name: Connect to Jenkins
    pause:
      prompt: "Have you connected to Jenkins to get initial password created? If so, Type 'Yes'"
      echo: Yes
  - name: Find out what the remote machine's mounts are
    slurp:
      src: /var/lib/jenkins/secrets/initialAdminPassword
    register: adminpasswordfile
  - debug:
      msg: "{{ adminpasswordfile['content'] | b64decode | replace('\n', '')}}"
