---
- name: Install Jenkins on EC2
  hosts: amazon
  become: true
  become_user: root
 
  tasks:
  - name: upgrade all packages
    yum :
      name: '*'
      state: latest
  - name: install openJDK
    yum :
      name: java-1.8.0-openjdk
      state: latest
  - name: Set java alternatives
    alternatives :
      name: java
      path: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
  - name: Remove Java 1.7.0
    yum :
      name: java-1.7.0-openjdk
      state: removed
  - name: Download Jenkins
    get_url:
      url : http://pkg.jenkins.io/redhat/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Install Jenkins
    shell : |
      rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
      yum install jenkins -y
      service jenkins start
  - name: Connect to Jenkins
    pause:
      prompt: "Have you connected to Jenkins to get initial password created? If so, Type 'Yes'"
      echo: Yes
  - name: Find out what the remote machine's mounts are
    slurp:
      src: /var/lib/jenkins/secrets/initialAdminPassword
    register: adminpasswordfile
  - debug:
      msg: "{{ adminpasswordfile['content'] | b64decode }}"
